# Generated by Django 5.2.12 on 2026-04-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_sessions', '0006_session_context_task_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasaRanking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ranked_items', models.JSONField(help_text='Lista ordinata dei 15 oggetti (posizione 0 = piu importante).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nasa_ranking', to='ai_sessions.session')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nasa_rankings_submitted', to='ai_sessions.sessionparticipant')),
            ],
            options={
                'db_table': 'tasks_nasa_ranking',
            },
        ),
    ]
