# Generated by Django 5.2.12 on 2026-04-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_create_nasaranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasaranking',
            name='is_final',
            field=models.BooleanField(default=False, help_text="True quando l'host ha confermato il ranking in fase CONCLUSION."),
        ),
    ]
