# Generated by Django 5.2.13 on 2026-04-21 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sessions', '0006_session_context_task_key'),
        ('tasks', '0002_add_is_final_to_nasaranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostAtSeaRanking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ranked_items', models.JSONField(help_text='Lista ordinata dei 15 oggetti (posizione 0 = piu importante).')),
                ('is_final', models.BooleanField(default=False, help_text="True quando l'host ha confermato il ranking in fase CONCLUSION.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lost_at_sea_ranking', to='ai_sessions.session')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_at_sea_rankings_submitted', to='ai_sessions.sessionparticipant')),
            ],
            options={
                'db_table': 'tasks_lost_at_sea_ranking',
            },
        ),
    ]
