# Generated by Django 5.2.13 on 2026-05-05 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sessions', '0009_session_individual_ranking_started_at_and_more'),
        ('tasks', '0004_nasaindividualranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostAtSeaIndividualRanking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ranked_items', models.JSONField(help_text='Lista ordinata dei 15 oggetti (posizione 0 = più importante).')),
                ('is_submitted', models.BooleanField(default=False, help_text='True quando il partecipante ha confermato esplicitamente, oppure quando la fase è stata finalizzata.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_at_sea_individual_rankings', to='ai_sessions.sessionparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_at_sea_individual_rankings', to='ai_sessions.session')),
            ],
            options={
                'db_table': 'tasks_lost_at_sea_individual_ranking',
                'indexes': [models.Index(fields=['session', 'is_submitted'], name='tasks_lost__session_0d40d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'participant'), name='uniq_lost_at_sea_individual_ranking_per_participant')],
            },
        ),
    ]
