# Generated by Django 5.2.8 on 2025-11-11 16:42

import apps.sessions.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('context', models.CharField(choices=[('MURDER_MYSTERY', 'Murder Mystery'), ('THERAPEUTIC', 'Contesto terapeutico'), ('WORKPLACE', 'Contesto lavorativo'), ('ACADEMIC', 'Contesto accademico')], max_length=32)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('LOBBY', 'Lobby'), ('ACTIVE', 'Active'), ('CONCLUSION', 'Conclusion'), ('CLOSED', 'Closed')], default='DRAFT', max_length=16)),
                ('min_size', models.PositiveSmallIntegerField()),
                ('max_size', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('conclusion_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default=apps.sessions.models._generate_token, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='ai_sessions.session')),
            ],
            options={
                'db_table': 'invitation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CREATED', 'Created'), ('PUBLISHED', 'Published'), ('INVITE_CREATED', 'Invite created'), ('JOINED', 'Joined'), ('STARTED', 'Started'), ('CONCLUSION_AUTO', 'Conclusion (auto)'), ('CLOSED_AUTO', 'Closed (auto)')], max_length=32)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ai_sessions.session')),
            ],
            options={
                'db_table': 'session_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('HOST', 'Host'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ai_sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_participant',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['state'], name='session_state_a44651_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['host', 'state'], name='session_host_id_7b34d9_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['session'], name='invitation_session_17761b_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['session'], name='session_eve_session_7466c5_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['type'], name='session_eve_type_31a0de_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionparticipant',
            index=models.Index(fields=['session'], name='session_par_session_7e847a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionparticipant',
            index=models.Index(fields=['session', 'role'], name='session_par_session_729cdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'user')},
        ),
    ]
