# Generated by Django 5.2.8 on 2025-11-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='published_at',
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.CharField(choices=[('LOBBY', 'Lobby'), ('ACTIVE', 'Active'), ('CONCLUSION', 'Conclusion'), ('CLOSED', 'Closed')], default='LOBBY', max_length=16),
        ),
        migrations.AlterField(
            model_name='sessionevent',
            name='type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('INVITE_CREATED', 'Invite created'), ('JOINED', 'Joined'), ('STARTED', 'Started'), ('CONCLUSION_AUTO', 'Conclusion (auto)'), ('CLOSED_AUTO', 'Closed (auto)')], max_length=32),
        ),
    ]
