# Generated by Django 5.2.8 on 2025-11-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sessions', '0002_remove_session_published_at_alter_session_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipant',
            name='ready_to_conclude',
            field=models.BooleanField(default=False),
        ),
    ]
