# Generated by Django 5.1.4 on 2026-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sessions', '0003_sessionparticipant_ready_to_conclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='final_summary',
            field=models.TextField(blank=True, help_text='Summary finale della sessione dal moderatore AI', null=True),
        ),
    ]
