# Generated by Django 5.2.10 on 2026-01-30 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sessions', '0004_add_final_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='report_text',
            field=models.TextField(blank=True, default='', help_text='Testo del report generato da LLM alla chiusura'),
        ),
        migrations.CreateModel(
            name='SessionVote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('suspect_chosen', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ai_sessions.sessionparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ai_sessions.session')),
            ],
            options={
                'db_table': 'session_vote',
                'indexes': [models.Index(fields=['session'], name='session_vot_session_c62992_idx')],
                'unique_together': {('session', 'participant')},
            },
        ),
    ]
