# Generated by Django 5.2.13 on 2026-04-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sessions', '0006_session_context_task_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='report_data',
            field=models.JSONField(blank=True, default=None, help_text='Dati strutturati del report (partecipazione, Gini, etc.)', null=True),
        ),
    ]
