# Generated by Django 5.2.13 on 2026-05-05 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sessions', '0007_add_session_report_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveBigIntegerField(help_text='Counter monotono per sessione, atomic via Redis INCR. Garantisce ordering robusto anche con timestamp identici.')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text="UTC con microsecondi, momento di registrazione dell'evento.")),
                ('event_type', models.CharField(choices=[('human_turn', 'Human turn'), ('ai_intervention', 'AI intervention'), ('system', 'System event')], max_length=32)),
                ('content', models.TextField(blank=True, default='', help_text='HUMAN_TURN: trascrizione del turno (può essere vuota se ASR non ha trascritto nulla). AI_INTERVENTION: messaggio del moderatore (vuoto se reason=all_ok o intervento bloccato senza testo). SYSTEM: descrizione human-readable.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Campi specifici per event_type. Vedi event_log.py per lo schema atteso di ciascun tipo.')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_events', to='ai_sessions.session')),
                ('speaker', models.ForeignKey(blank=True, help_text='Per HUMAN_TURN: chi ha parlato. Per AI_INTERVENTION: lo speaker del turno PRECEDENTE che ha innescato la decisione del moderatore. NULL per SYSTEM events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_events_as_speaker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_discussion_event',
                'ordering': ['session', 'sequence_number'],
                'indexes': [models.Index(fields=['session', 'sequence_number'], name='session_dis_session_c9ee4c_idx'), models.Index(fields=['session', 'event_type'], name='session_dis_session_14a0f7_idx'), models.Index(fields=['session', 'timestamp'], name='session_dis_session_905a66_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'sequence_number'), name='uniq_discussion_event_seq_per_session')],
            },
        ),
    ]
