# Generated by Django 5.2.13 on 2026-05-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sessions', '0008_discussionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='individual_ranking_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp di inizio fase INDIVIDUAL_RANKING. NULL per sessioni senza questa fase. Usato per calcolo timer 8 min.', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.CharField(choices=[('LOBBY', 'Lobby'), ('INDIVIDUAL_RANKING', 'Individual ranking'), ('ACTIVE', 'Active'), ('CONCLUSION', 'Conclusion'), ('CLOSED', 'Closed')], default='LOBBY', max_length=32),
        ),
    ]
