# Generated by Django 5.2.13 on 2026-05-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sessions', '0009_session_individual_ranking_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='moderator_enabled',
            field=models.BooleanField(default=True, help_text="Se False, la sessione gira in modalità 'no moderator': intro pronunciata regolarmente, ma niente LLM moderation calls né interventi vocali del moderatore durante la discussione e la conclusion. Usato per il braccio di controllo del design sperimentale within-subject (NASA Moon + Lost at Sea con moderatore ON/OFF, ordine controbilanciato). Immutabile dopo creazione."),
        ),
    ]
